load('Clay_2C-AA_take2_best_fit_parameters.rda')

## First, compare the Linf values calculated by Adriana for the raw
## data to the Linf value fitted to the trajectory generated by the
## best fit parameter set. Similar for eggrate
par(mfrow=c(1,2), oma=c(0.5,0.5,2,0.5), mar=c(5,5,0.5,0.5))
plot(p$Linf, p$predLinf, pch=21, bg=1, xlab=expression('Adriana'~~L[inf]), ylab=expression('Best fit trajectory'~~L[inf]))
points(seq(0,5,0.1),seq(0,5,0.1),type='l',col=2)
plot(p$Eggrate, p$predEggrate, pch=21, bg=1, xlab='Adriana Eggrate', ylab='Best fit trajectory Eggrate')
points(seq(0,5,0.1),seq(0,5,0.1),type='l',col=2)
mtext(side=3, outer=T, 'Genotype 2C')

## Two weird points
which(p$predEggrate > 1 & p$Eggrate < 0.5) ## 46
which(p$predLinf < 1.9 & p$Linf < 2.2) ## 24
## 24 is pretty poorly fit, looking at the trajectory against the data


